stages:
- build
- test

build:
  stage: build
  image: registry.gitlab.com/pwolf15/leetcode/cpp-dev:latest
  script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  artifacts:
    paths:
    - build

test:
  stage: test
  image: registry.gitlab.com/pwolf15/leetcode/cpp-dev:latest
  script:
  - cd build
  - ../resources/scripts/runTests
  dependencies:
  - build
