stages:
- build
- test
- scan

build:
  stage: build
  image: registry.gitlab.com/pwolf15/leetcode/cpp-dev:latest
  script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  artifacts:
    paths:
    - build
  only:
    - master
    - merge_requests

test:
  stage: test
  image: registry.gitlab.com/pwolf15/leetcode/cpp-dev:latest
  script:
  - cd build
  - ../resources/scripts/runTests
  dependencies:
  - build
  only:
    - master
    - merge_requests

scan:
  stage: scan
  image: registry.gitlab.com/pwolf15/leetcode/cpp-dev:latest
  script:
    - cppcheck --enable=all .
  only:
    - master
    - merge_requests